function FAT = FAT_init(FAT, FOV, system)

%% FAT saturation
if strcmp(FAT.mode, 'on')

    %  http://mriquestions.com/uploads/3/4/5/7/34572113/fat-water_review_jmri.21895.pdf
    FAT.ppm   = -3.45;        % [ppm] chemical shift of fat fraction
    FAT.df0   = FAT.ppm *1e-6 * system.B0 * system.gamma;
    if ~isfield(FAT, 'tExc')
        FAT.tExc  = 8  *1e-3;     % [s] pulse duration
    end
    if ~isfield(FAT, 'alpha')
        FAT.alpha = 100 *pi/180;  % [deg] flip angle
    end
    if ~isfield(FAT,'rf_type')
        FAT.rf_type = 'slr'; % default
    end

    if strcmp(FAT.rf_type, 'slr')
        FAT.rf = SIGPY_SLR(  FAT.alpha, ...
                             FAT.tExc,  ...
                             0,  ...
                             abs(FAT.tExc * FAT.df0) ,  ...
                             'sat',  ...
                             'ls',  ...
                             0.01, 0.01, ...
                             0 ,  ...
                             1e6,  ...
                             system);
        FAT.rf.freqOffset = FAT.df0;
    end

    if strcmp(FAT.rf_type, 'gauss')
        FAT.rf    = mr.makeGaussPulse(  FAT.alpha, system, ...
                                        'Duration', FAT.tExc, ...
                                        'bandwidth', abs(FAT.df0), ...
                                        'freqOffset', FAT.df0, ...
                                        'SliceThickness', 1e6, ...
                                        'PhaseOffset', 0, ...
                                        'use', 'saturation' );
    end
    
    if strcmp(FAT.rf_type, 'sinc')
        FAT.rf    = mr.makeSincPulse(   FAT.alpha, system, ...
                                        'Duration', FAT.tExc, ...
                                        'timeBwProduct', abs(FAT.tExc * FAT.df0), ...
                                        'freqOffset', FAT.df0, ...
                                        'SliceThickness', 1e6, ...
                                        'PhaseOffset', 0 , ...
                                        'use', 'saturation' );
    end

    FAT.crush_nTwist = 5; % [] number of 2pi twists in slice thickness
    FAT.crush_area   = FAT.crush_nTwist / FOV.dz;  % [1/m]
    FAT.gz_crush     = mr.makeTrapezoid('z', 'Area', FAT.crush_area, 'maxGrad', system.maxGrad/sqrt(3), 'maxSlew', system.maxSlew/sqrt(3), 'system', system);
    FAT.tcrush       = mr.calcDuration(FAT.gz_crush);

end

end